import { test, expect } from '@playwright/test'

test('custom opportunity picker supports keyboard selection and dismissal', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/#community')
  await page.locator('[data-ready="true"]').waitFor()
  const trigger = page.getByRole('button', { name: 'Opportunity type: All opportunities' })
  await trigger.click()
  await expect(page.getByRole('listbox', { name: 'Opportunity type' })).toBeVisible()
  await page.keyboard.press('w')
  await expect(page.getByRole('option', { name: 'Workshop', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  const selected = page.getByRole('button', { name: 'Opportunity type: Workshop' })
  await expect(selected).toBeFocused()
  await selected.press('ArrowDown')
  await page.keyboard.press('Escape')
  await expect(selected).toBeFocused()
  await selected.click()
  await page.getByRole('searchbox').click()
  await expect(page.getByRole('listbox')).toHaveCount(0)
})

test('project panels animate and closed content cannot receive focus', async ({ page }) => {
  await page.goto('/#research')
  const toggle = page.locator('#research button[aria-controls]').first()
  const panel = page.locator(`#${await toggle.getAttribute('aria-controls')}`)
  await expect(panel).toHaveAttribute('inert', '')
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-expanded', 'true')
  await expect(panel).not.toHaveAttribute('inert', '')
  await expect(panel).toHaveCSS('opacity', '1')
  await toggle.click()
  await expect(panel).toHaveAttribute('inert', '')
  await expect(panel).toHaveCSS('opacity', '0')
})
